version: "3"
services:
  venture-rockets:
    image: ghcr.io/tilakkap/venture-rockets:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.venture-rockets.rule=Host(`vr.hoppe.icu`)"
      - "traefik.http.routers.venture-rockets.entrypoints=websecure"
      - "traefik.http.routers.venture-rockets.tls=true"
      - "traefik.http.routers.venture-rockets.tls.certresolver=myresolver"
    networks:
      - traefik

networks:
  traefik:
    external: true
