name: Publish Docker image to GHCR

on:
  push:
    branches:
      - main
env:  # Define environment variables at the workflow level
  VPS_DIRECTORY: /home/thomas/docker/venture-rockets
  VPS_HOST: hoppe.icu
  VPS_USER: thomas

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: https://ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        push: true
        tags: ghcr.io/tilakkap/venture-rockets:latest


  # Step to create the directory if it doesn't exist
    - name: Create directory on VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: hoppe.icu
        username: ${{ env.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          mkdir -p ${{ env.VPS_DIRECTORY }}

    - name: Copy docker-compose.yml to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ env.VPS_HOST }}
        username: ${{ env.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: ./docker-compose.yml
        target: ${{ env.VPS_DIRECTORY }}/
        overwrite: true

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: hoppe.icu
        username: ${{ env.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          mkdir -p ${{ env.VPS_DIRECTORY }}
          cd ${{ env.VPS_DIRECTORY }}
          docker login --username tilakkap --password ${{ secrets.GHRC_SECRET }} ghcr.io
          docker compose pull
          docker compose up -d
        